[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Cristopher Namchee <cristophernamchee12@gmail.com"]
edition = "2018"

[dependencies]
regex = "1"

[[bin]]
name = "day-4-part-2"
path = "day4/main2.rs"